In [24]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_excel("/home/akshay/Projects/MitoCancer/data/Human.MitoCarta3.0.xls", sheet_name = 2)

In [26]:
data.head()

,HumanGeneID,MouseOrthologGeneID,Symbol,Synonyms,Description,MitoCarta3.0_List,MitoCarta3.0_Evidence,MitoCarta3.0_SubMitoLocalization,MitoCarta3.0_MitoPathways,TrainingDataset,...,liver_total_peak_intensity_log10,heart_total_peak_intensity_log10,skeletalmuscle_total_peak_intensity_log10,adipose_total_peak_intensity_log10,smallintestine_total_peak_intensity_log10,largeintestine_total_peak_intensity_log10,stomach_total_peak_intensity_log10,placenta_total_peak_intensity_log10,testis_total_peak_intensity_log10,HPA_Main_Location_2020 (Reliability)
0,1537,66445.0,CYC1,MC3DN6|UQCR4,cytochrome c1,MitoCarta3.0,"literature, APEX_IMS, APEX_matrix, targetP sig...",MIM,OXPHOS > Complex III > CIII subunits | Metabol...,Tmito,...,10.0,10.4,9.8,10.1,10.2,10.2,10.0,10.0,9.8,Mitochondria (Supported)
1,6390,67680.0,SDHB,CWS2|IP|PGL4|SDH|SDH1|SDH2|SDHIP,succinate dehydrogenase complex iron sulfur su...,MitoCarta3.0,"literature, APEX_matrix, targetP signal+, yeas...",MIM,OXPHOS > Complex II > CII subunits | Metabolis...,Tmito,...,10.2,10.3,9.2,10.1,10.3,9.9,9.9,10.1,9.9,Mitochondria (Supported)
2,10229,12850.0,COQ7,CAT5|CLK-1|CLK1|COQ10D8,"coenzyme Q7, hydroxylase",MitoCarta3.0,"literature, targetP signal+, yeast mito homolo...",MIM,Metabolism > Metals and cofactors > Coenzyme Q...,Tmito,...,9.0,8.6,8.7,8.8,8.6,9.0,8.7,8.3,8.3,Plasma membrane (Approved)
3,6389,66945.0,SDHA,CMD1GG|FP|PGL5|SDH1|SDH2|SDHF,succinate dehydrogenase complex flavoprotein s...,MitoCarta3.0,"literature, APEX_matrix, targetP signal+, yeas...",MIM,OXPHOS > Complex II > CII subunits | Metabolis...,Tmito,...,10.5,10.7,10.6,10.6,10.7,10.6,10.5,10.4,10.4,Mitochondria (Supported)
4,7384,22273.0,UQCRC1,D3S3191|QCR1|UQCR1,ubiquinol-cytochrome c reductase core protein 1,MitoCarta3.0,"literature, APEX_matrix, targetP signal+, yeas...",MIM,"Protein import, sorting and homeostasis > Prot...",Tmito,...,10.0,10.8,10.3,10.1,10.6,10.2,10.3,10.2,9.9,Mitochondria (Supported)

In [27]:
data.columns

Index(['HumanGeneID', 'MouseOrthologGeneID', 'Symbol', 'Synonyms',
       'Description', 'MitoCarta3.0_List', 'MitoCarta3.0_Evidence',
       'MitoCarta3.0_SubMitoLocalization', 'MitoCarta3.0_MitoPathways',
       'TrainingDataset', 'MitoCarta2.0_Score', 'MitoCarta2.0_FDR',
       'MitoCarta2.0_List', 'MitoCarta2.0_Evidence',
       'EnsemblGeneID_mapping_version_20200130', 'UniProt', 'ProteinLength',
       'TargetP_Score', 'MitoDomain_Score', 'CoexpressionGnfN50_Score',
       'PGC_Induction_Score', 'YeastMitoHomolog_Score',
       'RickettsiaHomolog_Score', 'MSMS_Score', 'hg19_Chromosome',
       'hg19_Start', 'hg19_Stop', 'MSMS_NUM_TISSUES',
       'MSMS_NUM_PEPTIDES_UNIQUE', 'MSMS_NUM_SPECTRA', 'MSMS_TOTAL_INTENSITY',
       'MSMS_PERCENT_COVERAGE', 'Tissues',
       'cerebrum_total_peak_intensity_log10',
       'cerebellum_total_peak_intensity_log10',
       'brainstem_total_peak_intensity_log10',
       'spinalcord_total_peak_intensity_log10',
       'kidney_total_peak_intensity_log10', 'liver_total_peak_intensity_log10',
       'heart_total_peak_intensity_log10',
       'skeletalmuscle_total_peak_intensity_log10',
       'adipose_total_peak_intensity_log10',
       'smallintestine_total_peak_intensity_log10',
       'largeintestine_total_peak_intensity_log10',
       'stomach_total_peak_intensity_log10',
       'placenta_total_peak_intensity_log10',
       'testis_total_peak_intensity_log10',
       'HPA_Main_Location_2020 (Reliability)'],
      dtype='str')

In [28]:
data = data[
    [
        "HumanGeneID",
        "Symbol",
        "MouseOrthologGeneID",
        "Description",
        "UniProt",
        "MitoCarta3.0_MitoPathways",
        "MitoCarta2.0_Score",
        "TargetP_Score",
        "hg19_Chromosome",
        "EnsemblGeneID_mapping_version_20200130"
    ]
]

In [29]:
data.head()

,HumanGeneID,Symbol,MouseOrthologGeneID,Description,UniProt,MitoCarta3.0_MitoPathways,MitoCarta2.0_Score,TargetP_Score,hg19_Chromosome,EnsemblGeneID_mapping_version_20200130
0,1537,CYC1,66445.0,cytochrome c1,P08574,OXPHOS > Complex III > CIII subunits | Metabol...,43.6442,2.0,chr8,ENSG00000179091
1,6390,SDHB,67680.0,succinate dehydrogenase complex iron sulfur su...,P21912,OXPHOS > Complex II > CII subunits | Metabolis...,43.2272,1.0,chr1,ENSG00000117118
2,10229,COQ7,12850.0,"coenzyme Q7, hydroxylase",Q99807,Metabolism > Metals and cofactors > Coenzyme Q...,43.1028,1.0,chr16,ENSG00000167186
3,6389,SDHA,66945.0,succinate dehydrogenase complex flavoprotein s...,P31040,OXPHOS > Complex II > CII subunits | Metabolis...,42.9701,1.0,chr5,ENSG00000073578
4,7384,UQCRC1,22273.0,ubiquinol-cytochrome c reductase core protein 1,P31930,"Protein import, sorting and homeostasis > Prot...",42.9037,1.0,chr3,ENSG00000010256

In [30]:
data_dict = data.to_dict(orient='records')

In [31]:
data_dict

[{'HumanGeneID': 1537,
  'Symbol': 'CYC1',
  'MouseOrthologGeneID': 66445.0,
  'Description': 'cytochrome c1',
  'UniProt': 'P08574',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex III > CIII subunits | Metabolism > Metals and cofactors > Heme-containing proteins | Metabolism > Electron carriers > Cytochromes | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 43.6442,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr8',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000179091'},
 {'HumanGeneID': 6390,
  'Symbol': 'SDHB',
  'MouseOrthologGeneID': 67680.0,
  'Description': 'succinate dehydrogenase complex iron sulfur subunit B',
  'UniProt': 'P21912',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex II > CII subunits | Metabolism > Carbohydrate metabolism > TCA cycle | Metabolism > Metals and cofactors > Fe-S-containing proteins | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 43.2272,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr1',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000117118'},
 {'HumanGeneID': 10229,
  'Symbol': 'COQ7',
  'MouseOrthologGeneID': 12850.0,
  'Description': 'coenzyme Q7, hydroxylase',
  'UniProt': 'Q99807',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Coenzyme Q metabolism',
  'MitoCarta2.0_Score': 43.1028,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr16',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000167186'},
 {'HumanGeneID': 6389,
  'Symbol': 'SDHA',
  'MouseOrthologGeneID': 66945.0,
  'Description': 'succinate dehydrogenase complex flavoprotein subunit A',
  'UniProt': 'P31040',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex II > CII subunits | Metabolism > Carbohydrate metabolism > TCA cycle | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 42.9701,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr5',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000073578'},
 {'HumanGeneID': 7384,
  'Symbol': 'UQCRC1',
  'MouseOrthologGeneID': 22273.0,
  'Description': 'ubiquinol-cytochrome c reductase core protein 1',
  'UniProt': 'P31930',
  'MitoCarta3.0_MitoPathways': 'Protein import, sorting and homeostasis > Protein import and sorting > Preprotein cleavage | OXPHOS > Complex III > CIII subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 42.9037,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr3',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000010256'},
 {'HumanGeneID': 84274,
  'Symbol': 'COQ5',
  'MouseOrthologGeneID': 52064.0,
  'Description': 'coenzyme Q5, methyltransferase',
  'UniProt': 'Q5HYK3',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Coenzyme Q metabolism',
  'MitoCarta2.0_Score': 42.6477,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr12',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000110871'},
 {'HumanGeneID': 5160,
  'Symbol': 'PDHA1',
  'MouseOrthologGeneID': 18597.0,
  'Description': 'pyruvate dehydrogenase E1 subunit alpha 1',
  'UniProt': 'P08559',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Pyruvate metabolism',
  'MitoCarta2.0_Score': 42.5705,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chrX',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000131828'},
 {'HumanGeneID': 57017,
  'Symbol': 'COQ9',
  'MouseOrthologGeneID': 67914.0,
  'Description': 'coenzyme Q9',
  'UniProt': 'O75208',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Coenzyme Q metabolism',
  'MitoCarta2.0_Score': 42.301,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr16',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000088682'},
 {'HumanGeneID': 6182,
  'Symbol': 'MRPL12',
  'MouseOrthologGeneID': 56282.0,
  'Description': 'mitochondrial ribosomal protein L12',
  'UniProt': 'P52815',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > mtRNA metabolism > Transcription | Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 42.0393,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr17',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000262814'},
 {'HumanGeneID': 513,
  'Symbol': 'ATP5F1D',
  'MouseOrthologGeneID': 66043.0,
  'Description': 'ATP synthase F1 subunit delta',
  'UniProt': 'P30049',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex V > CV subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 42.0165,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr19',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000099624'},
 {'HumanGeneID': 9377,
  'Symbol': 'COX5A',
  'MouseOrthologGeneID': 12858.0,
  'Description': 'cytochrome c oxidase subunit 5A',
  'UniProt': 'P20674',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex IV > CIV subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 41.9796,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr15',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000178741'},
 {'HumanGeneID': 122961,
  'Symbol': 'ISCA2',
  'MouseOrthologGeneID': 74316.0,
  'Description': 'iron-sulfur cluster assembly 2',
  'UniProt': 'Q86U28',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Fe-S cluster biosynthesis | Metabolism > Metals and cofactors > Fe-S-containing proteins',
  'MitoCarta2.0_Score': 41.9677,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr14',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000165898'},
 {'HumanGeneID': 9512,
  'Symbol': 'PMPCB',
  'MouseOrthologGeneID': 73078.0,
  'Description': 'peptidase, mitochondrial processing subunit beta',
  'UniProt': 'O75439',
  'MitoCarta3.0_MitoPathways': 'Protein import, sorting and homeostasis > Protein import and sorting > Preprotein cleavage | Protein import, sorting and homeostasis > Protein homeostasis > Proteases',
  'MitoCarta2.0_Score': 41.6397,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr7',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000105819'},
 {'HumanGeneID': 7386,
  'Symbol': 'UQCRFS1',
  'MouseOrthologGeneID': 66694.0,
  'Description': 'ubiquinol-cytochrome c reductase, Rieske iron-sulfur polypeptide 1',
  'UniProt': 'P47985',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex III > CIII subunits | Metabolism > Metals and cofactors > Fe-S-containing proteins | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 40.7667,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr19',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000169021'},
 {'HumanGeneID': 498,
  'Symbol': 'ATP5F1A',
  'MouseOrthologGeneID': 11946.0,
  'Description': 'ATP synthase F1 subunit alpha',
  'UniProt': 'P25705',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex V > CV subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 40.7095,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr18',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000152234'},
 {'HumanGeneID': 4967,
  'Symbol': 'OGDH',
  'MouseOrthologGeneID': 18293.0,
  'Description': 'oxoglutarate dehydrogenase',
  'UniProt': 'Q02218',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > TCA cycle',
  'MitoCarta2.0_Score': 40.5677,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr7',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000105953'},
 {'HumanGeneID': 5162,
  'Symbol': 'PDHB',
  'MouseOrthologGeneID': 68263.0,
  'Description': 'pyruvate dehydrogenase E1 subunit beta',
  'UniProt': 'P11177',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Pyruvate metabolism',
  'MitoCarta2.0_Score': 40.5677,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr3',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000168291'},
 {'HumanGeneID': 7385,
  'Symbol': 'UQCRC2',
  'MouseOrthologGeneID': 67003.0,
  'Description': 'ubiquinol-cytochrome c reductase core protein 2',
  'UniProt': 'P22695',
  'MitoCarta3.0_MitoPathways': 'Protein import, sorting and homeostasis > Protein import and sorting > Preprotein cleavage | OXPHOS > Complex III > CIII subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 40.5677,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr16',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000140740'},
 {'HumanGeneID': 6392,
  'Symbol': 'SDHD',
  'MouseOrthologGeneID': 66925.0,
  'Description': 'succinate dehydrogenase complex subunit D',
  'UniProt': 'O14521',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex II > CII subunits | Metabolism > Carbohydrate metabolism > TCA cycle | Metabolism > Metals and cofactors > Heme-containing proteins | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 40.1392,
  'TargetP_Score': 3.0,
  'hg19_Chromosome': 'chr11',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000204370'},
 {'HumanGeneID': 60488,
  'Symbol': 'MRPS35',
  'MouseOrthologGeneID': 232536.0,
  'Description': 'mitochondrial ribosomal protein S35',
  'UniProt': 'P82673',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 39.6435,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr12',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000061794'},
 {'HumanGeneID': 27089,
  'Symbol': 'UQCRQ',
  'MouseOrthologGeneID': 22272.0,
  'Description': 'ubiquinol-cytochrome c reductase complex III subunit VII',
  'UniProt': 'O14949',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex III > CIII subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 39.3103,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr5',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000164405'},
 {'HumanGeneID': 116540,
  'Symbol': 'MRPL53',
  'MouseOrthologGeneID': 68499.0,
  'Description': 'mitochondrial ribosomal protein L53',
  'UniProt': 'Q96EL3',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 39.3103,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr2',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000204822'},
 {'HumanGeneID': 1629,
  'Symbol': 'DBT',
  'MouseOrthologGeneID': 13171.0,
  'Description': 'dihydrolipoamide branched chain transacylase E2',
  'UniProt': 'P11182',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Amino acid metabolism > Branched-chain amino acid metabolism | Metabolism > Amino acid metabolism > Branched-chain amino acid dehydrogenase complex',
  'MitoCarta2.0_Score': 39.2448,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr1',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000137992'},
 {'HumanGeneID': 5166,
  'Symbol': 'PDK4',
  'MouseOrthologGeneID': 27273.0,
  'Description': 'pyruvate dehydrogenase kinase 4',
  'UniProt': 'Q16654',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Pyruvate metabolism',
  'MitoCarta2.0_Score': 38.7139,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr7',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000004799'},
 {'HumanGeneID': 4191,
  'Symbol': 'MDH2',
  'MouseOrthologGeneID': 17448.0,
  'Description': 'malate dehydrogenase 2',
  'UniProt': 'P40926',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Gluconeogenesis | Metabolism > Carbohydrate metabolism > Malate-aspartate shuttle | Metabolism > Carbohydrate metabolism > TCA cycle',
  'MitoCarta2.0_Score': 38.3734,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr7',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000146701'},
 {'HumanGeneID': 23107,
  'Symbol': 'MRPS27',
  'MouseOrthologGeneID': 218506.0,
  'Description': 'mitochondrial ribosomal protein S27',
  'UniProt': 'Q92552',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 38.3207,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr5',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000113048'},
 {'HumanGeneID': 1431,
  'Symbol': 'CS',
  'MouseOrthologGeneID': 12974.0,
  'Description': 'citrate synthase',
  'UniProt': 'O75390',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > TCA cycle',
  'MitoCarta2.0_Score': 37.826,
  'TargetP_Score': 3.0,
  'hg19_Chromosome': 'chr12',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000062485'},
 {'HumanGeneID': 80273,
  'Symbol': 'GRPEL1',
  'MouseOrthologGeneID': 17713.0,
  'Description': 'GrpE like 1, mitochondrial',
  'UniProt': 'Q9HAV7',
  'MitoCarta3.0_MitoPathways': 'Protein import, sorting and homeostasis > Protein import and sorting > Import motor | Metabolism > Metals and cofactors > Fe-S cluster biosynthesis',
  'MitoCarta2.0_Score': 37.8199,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr4',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000109519'},
 {'HumanGeneID': 1737,
  'Symbol': 'DLAT',
  'MouseOrthologGeneID': 235339.0,
  'Description': 'dihydrolipoamide S-acetyltransferase',
  'UniProt': 'P10515',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Pyruvate metabolism',
  'MitoCarta2.0_Score': 37.7551,
  'TargetP_Score': 4.0,
  'hg19_Chromosome': 'chr11',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000150768'},
 {'HumanGeneID': 10128,
  'Symbol': 'LRPPRC',
  'MouseOrthologGeneID': 72416.0,
  'Description': 'leucine rich pentatricopeptide repeat containing',
  'UniProt': 'P42704',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > mtRNA metabolism > mtRNA stability and decay | Mitochondrial central dogma > Translation',
  'MitoCarta2.0_Score': 37.7054,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr2',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000138095'},
 {'HumanGeneID': 1743,
  'Symbol': 'DLST',
  'MouseOrthologGeneID': 78920.0,
  'Description': 'dihydrolipoamide S-succinyltransferase',
  'UniProt': 'P36957',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > TCA cycle | Metabolism > Amino acid metabolism > Lysine metabolism',
  'MitoCarta2.0_Score': 37.6758,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr14',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000119689'},
 {'HumanGeneID': 8050,
  'Symbol': 'PDHX',
  'MouseOrthologGeneID': 27402.0,
  'Description': 'pyruvate dehydrogenase complex component X',
  'UniProt': 'O00330',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Pyruvate metabolism',
  'MitoCarta2.0_Score': 37.6758,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr11',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000110435'},
 {'HumanGeneID': 85476,
  'Symbol': 'GFM1',
  'MouseOrthologGeneID': 28030.0,
  'Description': 'G elongation factor mitochondrial 1',
  'UniProt': 'Q96RP9',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Translation factors',
  'MitoCarta2.0_Score': 37.4426,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr3',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000168827'},
 {'HumanGeneID': 25874,
  'Symbol': 'MPC2',
  'MouseOrthologGeneID': 70456.0,
  'Description': 'mitochondrial pyruvate carrier 2',
  'UniProt': 'O95563',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > Gluconeogenesis | Metabolism > Carbohydrate metabolism > Pyruvate metabolism | Metabolism > Carbohydrate metabolism > TCA-associated | Small molecule transport',
  'MitoCarta2.0_Score': 37.3563,
  'TargetP_Score': 5.0,
  'hg19_Chromosome': 'chr1',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000143158'},
 {'HumanGeneID': 4719,
  'Symbol': 'NDUFS1',
  'MouseOrthologGeneID': 227197.0,
  'Description': 'NADH:ubiquinone oxidoreductase core subunit S1',
  'UniProt': 'P28331',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex I > CI subunits | Metabolism > Metals and cofactors > Fe-S-containing proteins | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 36.8031,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr2',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000023228|ENSG00000283447'},
 {'HumanGeneID': 26589,
  'Symbol': 'MRPL46',
  'MouseOrthologGeneID': 67308.0,
  'Description': 'mitochondrial ribosomal protein L46',
  'UniProt': 'Q9H2W6',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 36.7746,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr15',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000259494'},
 {'HumanGeneID': 514,
  'Symbol': 'ATP5F1E',
  'MouseOrthologGeneID': 67126.0,
  'Description': 'ATP synthase F1 subunit epsilon',
  'UniProt': 'P56381',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex V > CV subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 36.4978,
  'TargetP_Score': 4.0,
  'hg19_Chromosome': 'chr20',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000124172'},
 {'HumanGeneID': 5250,
  'Symbol': 'SLC25A3',
  'MouseOrthologGeneID': 18674.0,
  'Description': 'solute carrier family 25 member 3',
  'UniProt': 'Q00325',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Copper metabolism | Signaling > Calcium homeostasis > Calcium cycle | Small molecule transport > SLC25A family',
  'MitoCarta2.0_Score': 36.4978,
  'TargetP_Score': 4.0,
  'hg19_Chromosome': 'chr12',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000075415'},
 {'HumanGeneID': 51649,
  'Symbol': 'MRPS23',
  'MouseOrthologGeneID': 64656.0,
  'Description': 'mitochondrial ribosomal protein S23',
  'UniProt': 'Q9Y3D9',
  'MitoCarta3.0_MitoPathways': 'Mitochondrial central dogma > Translation > Mitochondrial ribosome',
  'MitoCarta2.0_Score': 36.0922,
  'TargetP_Score': 5.0,
  'hg19_Chromosome': 'chr17',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000181610'},
 {'HumanGeneID': 2271,
  'Symbol': 'FH',
  'MouseOrthologGeneID': 14194.0,
  'Description': 'fumarate hydratase',
  'UniProt': 'P07954',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Carbohydrate metabolism > TCA cycle',
  'MitoCarta2.0_Score': 35.7616,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr1',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000091483'},
 {'HumanGeneID': 23203,
  'Symbol': 'PMPCA',
  'MouseOrthologGeneID': 66865.0,
  'Description': 'peptidase, mitochondrial processing subunit alpha',
  'UniProt': 'Q10713',
  'MitoCarta3.0_MitoPathways': 'Protein import, sorting and homeostasis > Protein import and sorting > Preprotein cleavage | Protein import, sorting and homeostasis > Protein homeostasis > Proteases',
  'MitoCarta2.0_Score': 35.653,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr9',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000165688'},
 {'HumanGeneID': 506,
  'Symbol': 'ATP5F1B',
  'MouseOrthologGeneID': 11947.0,
  'Description': 'ATP synthase F1 subunit beta',
  'UniProt': 'P06576',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex V > CV subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 35.6372,
  'TargetP_Score': 1.0,
  'hg19_Chromosome': 'chr12',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000110955'},
 {'HumanGeneID': 135154,
  'Symbol': 'SDHAF4',
  'MouseOrthologGeneID': 68002.0,
  'Description': 'succinate dehydrogenase complex assembly factor 4',
  'UniProt': 'Q5VUM1',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex II > CII assembly factors | OXPHOS > OXPHOS assembly factors',
  'MitoCarta2.0_Score': 35.5098,
  'TargetP_Score': 4.0,
  'hg19_Chromosome': 'chr6',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000154079'},
 {'HumanGeneID': 29796,
  'Symbol': 'UQCR10',
  'MouseOrthologGeneID': 66152.0,
  'Description': 'ubiquinol-cytochrome c reductase, complex III subunit X',
  'UniProt': 'Q9UDW1',
  'MitoCarta3.0_MitoPathways': 'OXPHOS > Complex III > CIII subunits | OXPHOS > OXPHOS subunits',
  'MitoCarta2.0_Score': 35.3274,
  'TargetP_Score': nan,
  'hg19_Chromosome': 'chr22',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000184076'},
 {'HumanGeneID': 81689,
  'Symbol': 'ISCA1',
  'MouseOrthologGeneID': 69046.0,
  'Description': 'iron-sulfur cluster assembly 1',
  'UniProt': 'Q9BUE6',
  'MitoCarta3.0_MitoPathways': 'Metabolism > Metals and cofactors > Fe-S cluster biosynthesis | Metabolism > Metals and cofactors > Fe-S-containing proteins',
  'MitoCarta2.0_Score': 35.264,
  'TargetP_Score': 2.0,
  'hg19_Chromosome': 'chr9',
  'EnsemblGeneID_mapping_version_20200130': 'ENSG00000135070'},
 {'HumanGeneID': 8803,